Jamalkhey/disable auto case indexation
powsybl/powsybl-case-server pull request #39
Opened 2024-08-01 08:01 UTC by jamal-khey

**Please check if the PR fulfills these requirements**

- [ ] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**Does this PR already have an issue describing the problem?**

**What kind of change does this PR introduce?**

**What is the current behavior?**

**What is the new behavior (if this is a feature change)?**

**Does this PR introduce a breaking change or deprecate an API?**
- [ ] Yes
- [ ] No

**If yes, please check if the following requirements are fulfilled**

- [ ] The *Breaking Change* or *Deprecated* label has been added
- [ ] The migration steps are described in the following section

**What changes might users need to make in their application due to this PR? (migration steps)**

**Other information**:

2024-08-14 14:09 UTC, SlimaneAmar requested changes

2024-08-16 11:16 UTC, jamal-khey commented on src/test/java/com/powsybl/caseserver/SupervisionControllerTest.java
> +@ContextConfigurationWithTestChannel
done partially , the tests does not pass without `properties = {"case-store-directory=/cases"}`

2024-08-18 19:12 UTC, jamal-khey commented on src/test/java/com/powsybl/caseserver/SupervisionControllerTest.java
> +        cleanDB();
done

2024-08-18 19:12 UTC, jamal-khey commented on src/test/java/com/powsybl/caseserver/SupervisionControllerTest.java
> +
done

2024-08-18 19:12 UTC, jamal-khey commented on src/test/java/com/powsybl/caseserver/SupervisionControllerTest.java
> +    public void testDeleteElementInfos() throws Exception {
done

2024-08-18 19:12 UTC, jamal-khey commented on src/test/java/com/powsybl/caseserver/SupervisionControllerTest.java
> +    public void testGetElementInfosCount() throws Exception {
done

2024-08-18 19:13 UTC, jamal-khey commented on src/main/java/com/powsybl/caseserver/CaseService.java
> +    @Transactional
done

2024-08-18 19:14 UTC, jamal-khey commented on src/main/java/com/powsybl/caseserver/CaseController.java
> +            @RequestParam(value = "withExpiration", required = false, defaultValue = "false") boolean withExpiration,
done

2024-08-18 19:15 UTC, jamal-khey commented on src/main/java/com/powsybl/caseserver/services/SupervisionService.java
> +    public long getIndexedCaseElementsCount() {
done

2024-08-18 19:15 UTC, jamal-khey commented on src/main/java/com/powsybl/caseserver/CaseController.java
> +        UUID caseUuid = caseService.importCase(file, withExpiration, indexed);
done

2024-08-18 19:15 UTC, jamal-khey commented on src/main/java/com/powsybl/caseserver/repository/CaseMetadataRepository.java
> +    List<CaseMetadataEntity> findAllById(Iterable<UUID> uuids);
done

2024-08-19 12:23 UTC, SlimaneAmar commented on src/main/java/com/powsybl/caseserver/CaseService.java
> +            Optional<CaseMetadataEntity> existingCase = caseMetadataRepository.findById(sourceCaseUuid);
Throws `NO_FOUND` exception like `disableCaseExpiration`

2024-08-19 12:24 UTC, SlimaneAmar commented
Remove any reference of the word `element`

2024-08-21 10:14 UTC, SlimaneAmar approved these changes

2024-08-21 12:51 UTC, merged